//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USBBackup.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USBBackup.Strings.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Backup.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one path must reference the device..
        /// </summary>
        public static string Backup_Validation_NoPathToDevice {
            get {
                return ResourceManager.GetString("Backup_Validation_NoPathToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory must be defined..
        /// </summary>
        public static string Backup_Validation_SourceNotSet {
            get {
                return ResourceManager.GetString("Backup_Validation_SourceNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target directory must be different..
        /// </summary>
        public static string Backup_Validation_SourceTargetEquals {
            get {
                return ResourceManager.GetString("Backup_Validation_SourceTargetEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory must be defined..
        /// </summary>
        public static string Backup_Validation_TargetNotSet {
            get {
                return ResourceManager.GetString("Backup_Validation_TargetNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string BackupSource {
            get {
                return ResourceManager.GetString("BackupSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string BackupTarget {
            get {
                return ResourceManager.GetString("BackupTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string MainWindow_ClosingSaveQuestion {
            get {
                return ResourceManager.GetString("MainWindow_ClosingSaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string MainWindow_ClosingSaveQuestion_Caption {
            get {
                return ResourceManager.GetString("MainWindow_ClosingSaveQuestion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new backup profile for this drive.
        /// </summary>
        public static string MainWindow_Tooltip_AddBackup {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_AddBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel running backup..
        /// </summary>
        public static string MainWindow_Tooltip_CancelBackup {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_CancelBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this backup profile.
        /// </summary>
        public static string MainWindow_Tooltip_DeleteBackup {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_DeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause running backup.
        /// </summary>
        public static string MainWindow_Tooltip_PauseBackup {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_PauseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all active backups.
        /// </summary>
        public static string MainWindow_Tooltip_RunAllBackups {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_RunAllBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start this backup.
        /// </summary>
        public static string MainWindow_Tooltip_RunBackup {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_RunBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all backup profiles.
        /// </summary>
        public static string MainWindow_Tooltip_Save {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the window to modify the application settings.
        /// </summary>
        public static string MainWindow_Tooltip_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Tooltip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run backups in fix intervals.
        /// </summary>
        public static string SettingsWindow_BackupOnInterval {
            get {
                return ResourceManager.GetString("SettingsWindow_BackupOnInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reject changes?.
        /// </summary>
        public static string SettingsWindow_CancelQuestion {
            get {
                return ResourceManager.GetString("SettingsWindow_CancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject changes?.
        /// </summary>
        public static string SettingsWindow_CancelQuestion_Caption {
            get {
                return ResourceManager.GetString("SettingsWindow_CancelQuestion_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up backup directories.
        /// </summary>
        public static string SettingsWindow_CleanupFolders {
            get {
                return ResourceManager.GetString("SettingsWindow_CleanupFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsWindow_Language {
            get {
                return ResourceManager.GetString("SettingsWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify about a completed backup.
        /// </summary>
        public static string SettingsWindow_NotifyBackupFinished {
            get {
                return ResourceManager.GetString("SettingsWindow_NotifyBackupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify about a started backup.
        /// </summary>
        public static string SettingsWindow_NotifyBackupStarted {
            get {
                return ResourceManager.GetString("SettingsWindow_NotifyBackupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify about a completed cleanup.
        /// </summary>
        public static string SettingsWindow_NotifyCleanupFinished {
            get {
                return ResourceManager.GetString("SettingsWindow_NotifyCleanupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify about a started cleanup.
        /// </summary>
        public static string SettingsWindow_NotifyCleanupStarted {
            get {
                return ResourceManager.GetString("SettingsWindow_NotifyCleanupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor backup folders for changes.
        /// </summary>
        public static string SettingsWindow_WatchFolders {
            get {
                return ResourceManager.GetString("SettingsWindow_WatchFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup to {0} finished..
        /// </summary>
        public static string TrayIcon_BackupFinished {
            get {
                return ResourceManager.GetString("TrayIcon_BackupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup finished.
        /// </summary>
        public static string TrayIcon_BackupFinished_Caption {
            get {
                return ResourceManager.GetString("TrayIcon_BackupFinished_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting backup to {0}..
        /// </summary>
        public static string TrayIcon_BackupStarted {
            get {
                return ResourceManager.GetString("TrayIcon_BackupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup started.
        /// </summary>
        public static string TrayIcon_BackupStarted_Caption {
            get {
                return ResourceManager.GetString("TrayIcon_BackupStarted_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Backups.
        /// </summary>
        public static string TrayIcon_CancelBackups {
            get {
                return ResourceManager.GetString("TrayIcon_CancelBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up of {0} finished..
        /// </summary>
        public static string TrayIcon_CleanUpFinished {
            get {
                return ResourceManager.GetString("TrayIcon_CleanUpFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up finished.
        /// </summary>
        public static string TrayIcon_CleanUpFinished_Caption {
            get {
                return ResourceManager.GetString("TrayIcon_CleanUpFinished_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up of {0} started..
        /// </summary>
        public static string TrayIcon_CleanUpStarted {
            get {
                return ResourceManager.GetString("TrayIcon_CleanUpStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up started.
        /// </summary>
        public static string TrayIcon_CleanUpStarted_Caption {
            get {
                return ResourceManager.GetString("TrayIcon_CleanUpStarted_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string TrayIcon_Close {
            get {
                return ResourceManager.GetString("TrayIcon_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TrayIcon_Open {
            get {
                return ResourceManager.GetString("TrayIcon_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Backups.
        /// </summary>
        public static string TrayIcon_PauseBackups {
            get {
                return ResourceManager.GetString("TrayIcon_PauseBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume backups.
        /// </summary>
        public static string TrayIcon_ResumeBackups {
            get {
                return ResourceManager.GetString("TrayIcon_ResumeBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Backups.
        /// </summary>
        public static string TrayIcon_RunBackups {
            get {
                return ResourceManager.GetString("TrayIcon_RunBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the copy process of the current file?.
        /// </summary>
        public static string UserChoice_HardCancel {
            get {
                return ResourceManager.GetString("UserChoice_HardCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UserChoice_HardCancel_Caption {
            get {
                return ResourceManager.GetString("UserChoice_HardCancel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this backup profile?.
        /// </summary>
        public static string UserChoice_RemoveBackup {
            get {
                return ResourceManager.GetString("UserChoice_RemoveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove backup profile?.
        /// </summary>
        public static string UserChoiceCaption_RemoveBackup {
            get {
                return ResourceManager.GetString("UserChoiceCaption_RemoveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup profiles successfully saved..
        /// </summary>
        public static string UserNotification_BackupsSaved {
            get {
                return ResourceManager.GetString("UserNotification_BackupsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups profile saved.
        /// </summary>
        public static string UserNotificationCaption_BackupsSaved {
            get {
                return ResourceManager.GetString("UserNotificationCaption_BackupsSaved", resourceCulture);
            }
        }
    }
}
